### ISSUE TITLE
ICEES SQLITE DB dependencies on identifiers.yaml

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-db#6]
This issue is to suggest that we remove the ICEES SQLITE DB dependencies on the identifiers.yaml files. ICEES KG pulls identifiers by leveraging the all_features.yml files and SRI services. ICEES+ no longer needs identifiers and so should not be dependent on the identifiers.yaml files.

**Comment by karafecho** [comment]
@hyi : It looks like I had already created a ticket for the identifiers.yaml issue. As we discussed, let's revisit this issue the next time we update any of the all_features YAML files.

**Comment by hyi** [comment]
@karafecho identifiers.yaml file dependency has been removed, so I am closing this issue.
